baseurl = "https://blognew.natt.cc/"
title = "Natt Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[permalinks]
  post = "/posts/:contentbasename/"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Natt Blog | Design & Life"
  description = "A blog about design, life, and technology."
  keyword = "Design, Life, Technology, Natt"
  slogan = "Stay hungry, stay foolish."
  
  image_404 = "img/404-bg.jpg"
  title_404 = "You are lost in the wilderness :("
  
  # Sidebar settings
  sidebar_about_description = "Designer & Life Adventurer"
  # sidebar_avatar = "img/avatar.jpg"

  featured_tags = true 
  featured_condition_size = 1 

  friends = false
  bookmarks = false
  about_me = true
  last_posts = true

  [params.social]
  rss            = true 
  github         = "https://github.com/nattli"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
